import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

// Normally resolves the host project's optional CSS build dependencies.
const dependencyDirectory = process.argv[2];
const require = createRequire(dependencyDirectory
  ? path.join(path.resolve(dependencyDirectory), 'package.json')
  : import.meta.url);
const postcss = require('postcss');
const tailwind = require('@tailwindcss/postcss');
const directory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceFile = path.join(directory, 'styles/tailwind.css');
const tailwindFile = require.resolve('tailwindcss/index.css').replaceAll('\\', '/');
const source = fs.readFileSync(sourceFile, 'utf8')
  .replace("@import 'tailwindcss'", `@import '${tailwindFile}'`);
const compiled = await postcss([tailwind({ base: directory, optimize: false })])
  .process(source, { from: sourceFile });
const css = compiled.root;
const scope = '.shc-dashboard';

// Unwrap Tailwind layers so the dashboard's scoped reset can override host defaults.
css.walkAtRules('layer', (rule) => {
  if (rule.nodes) rule.replaceWith(rule.nodes);
  else rule.remove();
});

css.walkRules((rule) => {
  let parent = rule.parent;
  while (parent && parent.type !== 'root') {
    // Nested selectors inherit the outer scope; keyframe steps are not selectors.
    if (parent.type === 'rule' || /keyframes$/.test(parent.name ?? '')) return;
    parent = parent.parent;
  }
  rule.selectors = rule.selectors.map((selector) => {
    if (selector === '.shc-dashboard-dark') return `${scope}.shc-dashboard-dark`;
    if (/^(?:html|body|:root|:host)(?=$|[\s[:.])/.test(selector)) {
      return selector.replace(/^(?:html|body|:root|:host)/, scope);
    }
    if (selector === '*') return `${scope}, ${scope} *`;
    if (selector === '::before' || selector === '::after') {
      return `${scope}${selector}, ${scope} ${selector}`;
    }
    return `${scope} ${selector}`;
  });
});

// Keep animation names and registered Tailwind properties separate from the host.
const animations = new Map();
css.walkAtRules('keyframes', (rule) => {
  const name = rule.params;
  animations.set(name, `shc-dashboard-${name}`);
  rule.params = animations.get(name);
});
css.walkDecls((declaration) => {
  if (!/animation|^--animate-/.test(declaration.prop)) return;
  for (const [name, replacement] of animations) {
    declaration.value = declaration.value.replace(new RegExp(`(?<![\\w-])${name}(?![\\w-])`, 'g'), replacement);
  }
});

const result = `/* Generated by scripts/build-styles.mjs. Styles are scoped to .shc-dashboard. */\n${css.toString()}
${scope} {
  display: block;
  width: 100%;
  min-width: 0;
  text-align: start;
  font-size: 16px;
  isolation: isolate;
}
${scope} button:not(:disabled), ${scope} [role="button"]:not(:disabled) { cursor: pointer; }
`;
fs.writeFileSync(path.join(directory, 'dashboard.css'), result.replaceAll('--tw-', '--shc-tw-'));
console.log('Built dashboard/dashboard.css with scoped styles.');
